import Head from "next/head";
import Image from "next/image";
import { useForm } from "react-hook-form";
import { useState } from "react";
export default function Home() {
	const [error, setError] = useState(null);
	const [isLoaded, setIsLoaded] = useState(false);
	const [items, setItems] = useState([]);
	const {
		register,
		handleSubmit,
		watch,
		formState: { errors },
	} = useForm();
	const handleClickSearch = async () => {
		const res = await fetch(
			"https://us-central1-ares-search.cloudfunctions.net/ares",
			{
				method: "POST",
				body: "08876100",
			}
		);
		const data = await res.json();
		console.log(data);
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="grid place-items-center min-h-screen">
				<div>
					<button onClick={handleClickSearch}>Ares</button>

					<h1 className="text-6xl pt-6 font-bold ">Ares výpis z rejstříku</h1>

					<form className="flex justify-center py-8  ">
						<input
							className="border-2 py-2  w-1/2 px-3 border-black"
							{...register("exampleRequired", { required: true })}
						/>
						{errors.exampleRequired && <span>Toto pole je povinné.</span>}

						<input
							className="border-2 py-2 border-black mx-4 px-3"
							type="submit"
						/>
					</form>
				</div>
			</main>

			<footer></footer>
		</div>
	);
}
