import Head from "next/head";
import Image from "next/image";
import { useForm } from "react-hook-form";
import { useState } from "react";
import TableData from "../components/TableData";
export default function Home() {
	const [error, setError] = useState(null);
	const [isLoaded, setIsLoaded] = useState(false);
	const [companyInfo, setCompanyInfo] = useState({});
	const [search, setSearch] = useState();
	const {
		register,
		handleSubmit,
		watch,
		formState: { errors },
	} = useForm();
	const onSubmit = async (form) => {
		const res = await fetch(
			"https://us-central1-ares-search.cloudfunctions.net/ares",
			{
				method: "POST",
				body: form.spolecnost,
			}
		);
		const data = await res.json();
		console.log(Array.isArray(data));
		if (Array.isArray(data)) {
			setCompanyInfo(data);
			console.log(companyInfo);
		} else {
			setCompanyInfo([data]);
			console.log(companyInfo);
		}
	};

	if (!companyInfo)
		return (
			<div>
				<Head>
					<title>Ares data</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className="grid place-items-center min-h-screen">
					<div>
						<h1 className="text-6xl pt-6 font-bold ">Ares výpis z rejstříku</h1>
						<form
							onSubmit={handleSubmit(onSubmit)}
							className="flex justify-center py-8  "
						>
							<input
								className="border-2 py-2  w-1/2 px-3 border-black"
								{...register("spolecnost", { required: true })}
							/>
							{errors.exampleRequired && <span>Toto pole je povinné.</span>}

							<input
								className="border-2 py-2 border-black mx-4 px-3"
								type="submit"
							/>
						</form>
						žadna data
					</div>
				</main>

				<footer></footer>
			</div>
		);
	if (companyInfo.length)
		return (
			<div>
				<Head>
					<title>Ares data</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className="grid place-items-center min-h-screen">
					<div>
						<h1 className="text-6xl pt-6 font-bold ">Ares výpis z rejstříku</h1>
						<form
							onSubmit={handleSubmit(onSubmit)}
							className="flex justify-center py-8  "
						>
							<input
								className="border-2 py-2  w-1/2 px-3 border-black"
								{...register("spolecnost", { required: true })}
							/>
							{errors.exampleRequired && <span>Toto pole je povinné.</span>}

							<input
								className="border-2 py-2 border-black mx-4 px-3"
								type="submit"
							/>
						</form>

						<TableData companies={companyInfo} />
					</div>
				</main>

				<footer></footer>
			</div>
		);

	return (
		<div>
			<Head>
				<title>Ares data</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="grid place-items-center min-h-screen">
				<div>
					<h1 className="text-6xl pt-6 font-bold ">Ares výpis z rejstříku</h1>
					<form
						onSubmit={handleSubmit(onSubmit)}
						className="flex justify-center py-8  "
					>
						<input
							className="border-2 py-2  w-1/2 px-3 border-black"
							{...register("spolecnost", { required: true })}
						/>
						{errors.exampleRequired && <span>Toto pole je povinné.</span>}

						<input
							className="border-2 py-2 border-black mx-4 px-3"
							type="submit"
						/>
					</form>
				</div>
			</main>

			<footer></footer>
		</div>
	);
}
